### ISSUE TITLE
Issue with Custom message - gps_agent_pkg.msg

### ISSUE THREAD

**Issue by sarveshj** [lakehanne/gps#1]
Hi Lakehanne,

Great work with adapting GPS for ROS indigo. I am currently trying to simulate the first example for ROS from gps documentation and am facing the following error

**ImportError: No module named gps_agent_pkg.msg**

Full traceback is below:

sarveshs@sarveshs-Lenovo-G570:~/catkin_ws/src/gps$ python python/gps/gps_main.py pr2_example
Traceback (most recent call last):
  File "python/gps/gps_main.py", line 410, in <module>
    main()
  File "python/gps/gps_main.py", line 344, in main
    hyperparams = imp.load_source('hyperparams', hyperparams_file)
  File "/home/sarveshs/catkin_ws/src/gps/experiments/pr2_example/hyperparams.py", line 10, in <module>
    from gps.agent.ros.agent_ros import AgentROS
  File "python/gps/agent/ros/agent_ros.py", line 11, in <module>
    from gps.agent.ros.ros_utils import ServiceEmulator, msg_to_sample, \
  File "python/gps/agent/ros/ros_utils.py", line 20, in <module>
    from gps_agent_pkg.msg import ControllerParams, LinGaussParams, TfParams, CaffeParams, TfActionCommand

ImportError: No module named gps_agent_pkg.msg

Do you have any suggestions? Thanks!

**Comment by robotsorcerer** [comment]
Did you do your PythonExports? You should add gps_agent_pkg to your `PYTHONPATH` like so:

```bash
export PYTHONPATH=${PYTHONPATH:+:${PYTHONPATH}}:/home/$USER/Documents/caffe/python
```

Remove the caffe part above if you plan to use Tensorflow. If you are using caffe, make sure the `home/$USER/Documents/caffe/python` points to your pycaffe installation path.

Also, do not forget to append `gps_agent_pkg` to your `ROS_PACKAGE_PATH`:

```bash
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/home/$USER/catkin_ws/src/gps/python/gps:/home/$USER/catkin_ws/src/gps/gps_agent_pkg
```

In addition, don't forget to build the gps_agent library. Make sure code is cloned to your catkin workspace `src` folder. Then you should [catkin build](http://catkin-tools.readthedocs.io/en/latest/quick_start.html#initializing-a-new-workspace)  `gps_agent_pkg` from your catkin workspace.

**Comment by sarveshj** [comment]
Hi Lakehanne,

Thanks for the suggestions :) I finally managed to get it working!! I am very much interested in original example of PR2 robot moving from a given position to target position. Could you please suggest how I can do that as the PR2 robot now just moves it arm? I am trying to look at code and figure it out and any suggestions would be helpful. Thanks!

**Comment by robotsorcerer** [comment]
You should look into the pr2_example [hyperparameters file](https://github.com/lakehanne/gps/blob/master/experiments/pr2_example/hyperparams.py#L28-#L30) and play with the end effector points. You might have to also specify changes in the [target.npz](https://github.com/lakehanne/gps/blob/master/experiments/pr2_example/target.npz) file where start and goal poses are saved by default.

Either way, nothing would substitute for reading the codebase and learning how the algorithm is implemented.

**Comment by best99317** [comment]
Hi @sarveshj ,
I am dealing with exactly the same problem. Can you explain how you got it working more specifically?
Thank you very much!
