### ISSUE TITLE
Caffe issues

### ISSUE THREAD

**Issue by SJTUzhanglj** [lakehanne/gps#2]
Hello, i'm a catkin+ros indigo user, and i'm glad to this repo.
But i met with some troubles about caffe, when execute cmake. command
is the installation step the same with the cbfinn's?
The cmake  info is:
zlj@zlj:~/code/RL/gps/gps_agent_pkg$ cmake . -DUSE_CAFFE=1 -DUSE_CAFFE_GPU=1 -DCAFFE_INCLUDE_PATH=/home/zlj/code/caffe/distribute/include -DCAFFE_LIBRARY_PATH=/home/zlj/code/caffe/build/lib
-- Using CATKIN_DEVEL_PREFIX: /home/zlj/code/RL/gps/gps_agent_pkg/devel
-- Using CMAKE_PREFIX_PATH: /home/zlj/catkin_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/zlj/catkin_ws/devel;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/zlj/code/RL/gps/gps_agent_pkg/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- Using these message generators: gencpp;geneus;genlisp;genpy
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "Caffe" with any of
  the following names:

    CaffeConfig.cmake
    caffe-config.cmake

  Add the installation prefix of "Caffe" to CMAKE_PREFIX_PATH or set
  "Caffe_DIR" to a directory containing one of the above files.  If "Caffe"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:26 (find_package)

-- Could not find the required component 'Caffe'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "Caffe" with any of
  the following names:

    CaffeConfig.cmake
    caffe-config.cmake

  Add the installation prefix of "Caffe" to CMAKE_PREFIX_PATH or set
  "Caffe_DIR" to a directory containing one of the above files.  If "Caffe"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:26 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/zlj/code/RL/gps/gps_agent_pkg/CMakeFiles/CMakeOutput.log".
See also "/home/zlj/code/RL/gps/gps_agent_pkg/CMakeFiles/CMakeError.log".
zlj@zlj:~/code/RL/gps/gps_agent_pkg$ cmake . 
-- Using CATKIN_DEVEL_PREFIX: /home/zlj/code/RL/gps/gps_agent_pkg/devel
-- Using CMAKE_PREFIX_PATH: /home/zlj/catkin_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/zlj/catkin_ws/devel;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/zlj/code/RL/gps/gps_agent_pkg/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- Using these message generators: gencpp;geneus;genlisp;genpy
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "Caffe" with any of
  the following names:

    CaffeConfig.cmake
    caffe-config.cmake

  Add the installation prefix of "Caffe" to CMAKE_PREFIX_PATH or set
  "Caffe_DIR" to a directory containing one of the above files.  If "Caffe"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:26 (find_package)

-- Could not find the required component 'Caffe'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "Caffe" with any of
  the following names:

    CaffeConfig.cmake
    caffe-config.cmake

  Add the installation prefix of "Caffe" to CMAKE_PREFIX_PATH or set
  "Caffe_DIR" to a directory containing one of the above files.  If "Caffe"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:26 (find_package)

looking forward to your reply

**Comment by robotsorcerer** [comment]
First of all, this code should be cloned to your `catkin workspace src` folder. You seem to have yours otherwise. When you installed `caffe` you should set the `caffe` path environmental variable in your `bash` as the [documentation](http://caffe.berkeleyvision.org/installation.html) explains. If you installed in the `Documents` folder for example, you should have done something of this sort:

`export CAFFE_ROOT=/home/$USER/Documents/caffe/build_cudnn/` 

in terminal or residing in your `bash` or `zsh` file. 

You would not need to explicitly use `cmake` in building the `gps_agent_pkg` library. Either one of [catkin_make](http://wiki.ros.org/catkin/commands/catkin_make) or [catkin build](http://catkin-tools.readthedocs.io/en/latest/verbs/catkin_build.html) would take care of those for you. 

If you want to explicitly turn on the caffe build parameters during compilation, you would do something of the following sort:

```bash
        catkin build --cmake-args -DUSE_CAFFE=ON
```

or you could explicitly edit the `gps_agent_pkg's` [CMakeLists.txt](https://github.com/lakehanne/gps/blob/master/gps_agent_pkg/CMakeLists.txt#L19) file.
